server:
  port: 8081
spring:
  profiles:
    group:
      default:
        - application
        - api
        - core
        - keycloak
        - mysql
        - oauth2
        - webapp
      development:
        - dev
        - api-dev
        - core-dev
        - keycloak-dev
        - mysql-dev
        - oauth2-dev
        - webapp-dev
